language: node_js
cache: false
node_js:
- stable
script:
- eslint 'src/**'
- npm run test:coveralls
deploy:
  provider: heroku
  api_key:
    secure: QH6IOd7EE/1AqdqX5L3OMZrIzvSRv5jgkeUUb5xAWtSwNNfM+dMlqp75gKL1/KkbqvkcWjTDML4U4q8kFGqbdqz7/ffiseUEX9pFGmOnaOoT4dgJNwg4ojAslWtMFQsoC4aRrZi0zHF7WfK0XMA2UAyYwHOTmgGM+FKXwqZBqZ5zUo96aAHQYxnGgd6/uaJ8vJyXXvVGrJybHDwwojqhBp0le+R0KajUiNUGGgafKuuqXteOFFF1tcYkDMZBaoNpyC5YPecrAOQAvSYaEqPKHoP0Sgp9GkDNUvPbTxwjwEaSYFd9pEGwtT6BJy3xzIDm041Gb2RZ2FPxMr0Cjh9MItF/3UtznZFk+xavRNWTwx96yBL4F7lI8YIfCJKT51QGxLaeMda1PC4h2y2knQO6QSFz0VLltBfmwcMXrDlwb7tZvw+68GDSCRzusHUEO2tb5DJg6Jbr/wtf6hmRfv8/gyAC4wsSbVlv1sWdcZK3uugrn3SRMxiBRWhDtmt3YoP4OtsBobhCqQMS3ksOzs19+ImaJvhJfzw5L0GIbIpWceatMWY3inmkhUQNrHvRSMgUsyznBLNdpNlLxbvs3DwbC7/bLbiozRzQ4W9EXX64nmuWMtBRli/0wfXQbh1o/H8Q4yddsnLFfmgUuAUjrgy1S8x6RYlm4pkRPPdOWpBwNHg=
  app:
    master: clean-express-api
  strategy: git
