language: node_js
cache: false
node_js:
- stable
script:
- eslint 'src/**'
- yarn test:coveralls
deploy:
  provider: heroku
  api_key:
    secure: kQP+75zk0zEqedAauXUVC01Lc+5MxhX8CgiwL63wh+G38M5Dvo0y12x7vkqaYQiHBeDwLLM9tmGTCk2dMhqHmcg5Ya47NyAt1umLV2li5x9nmfURlK/Owx4IeYE8mW73BnmoMb0jNJLBBW95AOo2UKt7QkMUcQB2z01cSkyun5GyuSprpZ0uCOeCEC56YtCvs5H8emb5grE96RfOhoSfu04jpeY8wVNc0OQwzpsnHf+c6XlBlNVvGME18u0PMzGswpQxRgOa9VQ2sjPksK7Cw7Op/k+aqeNvrsOtlacsPVo/qkfcxrffwkLISax6HaEXZKQr9eiUaJgT6ZvcuKpUrltfbtiKlxEsytVm4V0L0QtP6Nzci4hHhFlkBBOXaL7vXHrC9kuctqDQA3I4dSv9tsgQ/V4R3ojI+gPSFH2KT5dorBcm3yzn3//JtYT0l+eTgQsE3PSOhEsmUoVMInXUo/ABV8wuVVjJ27pXMfxuDDlrPF5E2W2JoUSWT9ZQ9ptCX3bSlr+Xzd12WSaGxHoI/0sV8DueX6OXaJDHSFMJSx9dQ9ZMuVKYBOX5cZKAecG4mjsIEfq94Y/fP8venVJEna9W/r6GAocGQ32mrCoTGPamo5TpNCLtlSDAY+bUQvqlP++r6j85MhVHYbwliCO5YHW4falpaext4KSBN3x+hXE=
  app:
    master: clean-express-api
  strategy: git
