version: "3"
services: 
  api:
    container_name: api-container
    build: .
    image: clean-node-api
    restart: always
    command: npm run debug
    volumes: 
      - ./dist:/usr/src/clean-node-api/dist
    ports: 
      - "5050:5050"
      - "9222:9222"
