version: "3"
services: 
  api:
    container_name: api-container
    image: node:16
    working_dir: /usr/src/clean-node-api
    restart: always
    command: bash -c "npm install --only=prod && npm run debug"
    volumes: 
      - ./dist/:/usr/src/clean-node-api/dist/
      - ./package.json:/usr/src/clean-node-api/package.json
      - ./.env:/usr/src/clean-node-api/.env
    ports: 
      - "5050:5050"
      - "9222:9222"

      #done
